import bets from '../data/bets.json'
import participants from '../data/participants.json'

type Tier='low'|'medium'|'high'
const tiers:Record<Tier,{label:string;hint:string;badge:string}>={
low:{label:'Cote basse',hint:'Challenger, victoire probable',badge:'bg-green-900/40 text-green-300 border-green-600/40'},
medium:{label:'Cote moyenne',hint:'Outsider, victoire possible',badge:'bg-blue-900/40 text-blue-300 border-blue-600/40'},
high:{label:'Cote élevée',hint:"Personne n'y croit, haut gain",badge:'bg-orange-900/40 text-orange-300 border-orange-600/40'}}
const kamas=(n:number)=>new Intl.NumberFormat('fr-FR').format(n).replace(/\u202f|\u00a0/g,' ')+' Kamas'
const rows=bets.betDetails.map(b=>{const t=participants.find(x=>x.id===b.teamId);return {...b,name:t?.displayName??b.teamId,classes:(t as {classes?:string[]}|undefined)?.classes??[],odds:bets.totalPot/b.amount}}).sort((a,b)=>a.odds-b.odds)
export default function Paris(){return <div className="min-h-screen"><div className="relative bg-gradient-to-b from-gray-900/95 to-gray-950 overflow-hidden"><div className="absolute inset-0 bg-[url('https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1920')] bg-cover bg-center opacity-10 blur-sm"/><div className="relative container mx-auto px-6 py-24"><p className="text-blue-400 font-semibold mb-4 text-sm uppercase tracking-wider">DOFUS - EVENT DUOTAGE GÉNÉRATION MIRACLE</p><h1 className="text-6xl md:text-7xl font-black mb-4 text-white">Paris du tournoi</h1><p className="text-xl text-gray-400 mb-8 max-w-2xl">Consultez les cotes actuelles et le détail des paris. Les données sont mises à jour manuellement et ne sont pas interactives.</p><div className="bg-gradient-to-r from-purple-900/30 to-pink-900/30 backdrop-blur-sm rounded-lg px-6 py-4 border border-purple-600/30 inline-block"><p className="text-sm text-purple-300 mb-1">Cagnotte totale de paris</p><p className="text-3xl font-black text-purple-300">{kamas(bets.totalPot)}</p></div></div></div><div className="container mx-auto px-6 py-12"><div className="mb-12 bg-yellow-900/20 border border-yellow-600/30 rounded-lg p-6"><p className="text-yellow-300 text-center font-semibold">ℹ️ Les cotes et mises sont mises à jour manuellement. Cette page est en lecture seule.</p></div>{rows.length===0?<div className="bg-gray-800/30 rounded-lg border border-gray-700 p-10 text-center text-gray-400">Aucun pari n'est actuellement renseigné.</div>:<><div className="mb-8 grid gap-3 md:grid-cols-3">{(Object.keys(tiers) as Tier[]).map(k=><div key={k} className={`rounded-lg border px-4 py-3 ${tiers[k].badge}`}><p className="font-bold">{tiers[k].label}</p><p className="text-sm opacity-80">{tiers[k].hint}</p></div>)}</div><div className="overflow-x-auto bg-gray-800/30 rounded-lg border border-gray-700"><table className="w-full text-left"><thead><tr className="border-b border-gray-700 text-sm uppercase tracking-wider text-gray-400"><th className="px-6 py-4">Équipe</th><th className="px-6 py-4">Classes</th><th className="px-6 py-4 text-right">Paris</th><th className="px-6 py-4 text-right">Cote</th></tr></thead><tbody>{rows.map(r=><tr key={r.teamId} className="border-b border-gray-800 last:border-0"><td className="px-6 py-4 font-bold text-white">{r.name}</td><td className="px-6 py-4 text-gray-300">{r.classes.join(' + ')}</td><td className="px-6 py-4 text-right text-gray-300 whitespace-nowrap">{kamas(r.amount)}</td><td className="px-6 py-4 text-right"><span className={`inline-block rounded border px-3 py-1 font-bold whitespace-nowrap ${tiers[r.tier as Tier].badge}`}>x {r.odds.toFixed(2).replace('.',',')}</span></td></tr>)}</tbody></table></div></>}</div></div>}
